/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import Organos.*;
import Organos.Organo;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Owner
 */
public class Clase_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Clase_Principal
     */
    ArrayList<Doctor> doctores = new ArrayList();

    public Clase_Principal() {
        initComponents();

    }

    public void Recargar() {
        DefaultTreeModel m = (DefaultTreeModel) jt_doctores.getModel();
        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
        raiz.removeAllChildren();
        for (Doctor dt : doctores) {
            DefaultMutableTreeNode doctor = new DefaultMutableTreeNode(dt);
            for (Paciente pac : dt.getPacientes()) {
                DefaultMutableTreeNode paciente = new DefaultMutableTreeNode("Paciente: " + pac);
                DefaultMutableTreeNode o = new DefaultMutableTreeNode("Organos");
                for (Organo lO : pac.getListaOrganos()) {
                    DefaultMutableTreeNode organo = new DefaultMutableTreeNode(lO);

                    o.add(organo);
                }
                paciente.add(o);
                DefaultMutableTreeNode a = new DefaultMutableTreeNode("Alergias");
                for (String alergia : pac.getAlergias()) {
                    DefaultMutableTreeNode alergias = new DefaultMutableTreeNode(alergia);

                    a.add(alergias);
                }
                paciente.add(a);
                DefaultMutableTreeNode e = new DefaultMutableTreeNode("Enfermedades");
                for (String enf : pac.getEnfermedades()) {
                    DefaultMutableTreeNode enfermedad = new DefaultMutableTreeNode(enf);

                    e.add(enfermedad);
                }
                paciente.add(e);
                doctor.add(paciente);

            }

            raiz.add(doctor);

        }
        m.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        t2_nombre = new javax.swing.JTextField();
        t2_edad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t2_altura = new javax.swing.JTextField();
        t2_id = new javax.swing.JTextField();
        t2_peso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Femenino = new javax.swing.JRadioButton();
        Masculino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        t2_ingreso = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        rb_sexo = new javax.swing.ButtonGroup();
        jd_agregar_doctor = new javax.swing.JDialog();
        t1_nombre = new javax.swing.JTextField();
        t1_edad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t1_altura = new javax.swing.JTextField();
        t1_id = new javax.swing.JTextField();
        t1_peso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        femenino = new javax.swing.JRadioButton();
        masculino = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        t1_anios = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        t1_entrada = new javax.swing.JTextField();
        t1_salida = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lu = new javax.swing.JCheckBox();
        sa = new javax.swing.JCheckBox();
        vi = new javax.swing.JCheckBox();
        ju = new javax.swing.JCheckBox();
        mi = new javax.swing.JCheckBox();
        ma = new javax.swing.JCheckBox();
        dom = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_especialidad = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        rb_sexo2 = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_doctores = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        cb_pacientes = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        bt_organo = new javax.swing.JButton();
        jb_alergia = new javax.swing.JButton();
        bt_enfermedad = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Agregar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        t2_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2_nombreKeyTyped(evt);
            }
        });

        t2_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2_edadKeyTyped(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Listo");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nuevo Paciente");

        jLabel4.setText("ID");

        t2_altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2_alturaKeyTyped(evt);
            }
        });

        t2_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2_idKeyTyped(evt);
            }
        });

        t2_peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2_pesoKeyTyped(evt);
            }
        });

        jLabel5.setText("Peso");

        jLabel6.setText("Altura");

        rb_sexo.add(Femenino);
        Femenino.setText("F");

        rb_sexo.add(Masculino);
        Masculino.setSelected(true);
        Masculino.setText("M");

        jLabel7.setText("Sexo");

        jLabel8.setText("Fecha de Ingreso");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(85, 85, 85)
                        .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t2_edad, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(t2_nombre)
                            .addComponent(t2_peso, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(t2_altura, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(t2_id, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(jd_agregarLayout.createSequentialGroup()
                                .addComponent(Masculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Femenino))
                            .addComponent(t2_ingreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jd_agregarLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel3)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2_peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Masculino)
                    .addComponent(jLabel7)
                    .addComponent(Femenino))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t2_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jd_agregar_doctor.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_nombreKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 150, -1));

        t1_edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_edadKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 117, 150, -1));

        jLabel10.setText("Nombre");
        jd_agregar_doctor.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 80, -1, -1));

        jLabel11.setText("Edad");
        jd_agregar_doctor.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 120, -1, -1));

        guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, -1, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Nuevo un Doctor");
        jd_agregar_doctor.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        jLabel13.setText("ID");
        jd_agregar_doctor.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 158, -1, -1));

        t1_altura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_alturaKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 204, 150, -1));

        t1_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_idKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 155, 150, -1));

        t1_peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_pesoKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 242, 150, -1));

        jLabel14.setText("Peso");
        jd_agregar_doctor.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 245, -1, -1));

        jLabel15.setText("Altura");
        jd_agregar_doctor.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 204, -1, -1));

        rb_sexo2.add(femenino);
        femenino.setText("F");
        jd_agregar_doctor.getContentPane().add(femenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 76, -1, -1));

        rb_sexo2.add(masculino);
        masculino.setSelected(true);
        masculino.setText("M");
        jd_agregar_doctor.getContentPane().add(masculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 76, -1, -1));

        jLabel16.setText("Sexo");
        jd_agregar_doctor.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 80, -1, -1));

        jLabel17.setText("Años de trabajo");
        jd_agregar_doctor.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 120, -1, -1));

        t1_anios.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_aniosKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_anios, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 117, 135, -1));

        jLabel18.setText("Hora de entrada");
        jd_agregar_doctor.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 207, -1, -1));

        jLabel19.setText("Hora de salida");
        jd_agregar_doctor.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 245, -1, -1));

        t1_entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_entradaKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_entrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 204, 135, -1));

        t1_salida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t1_salidaKeyTyped(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(t1_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 242, 135, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 80, 40));

        lu.setText("Lunes");
        jd_agregar_doctor.getContentPane().add(lu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 311, -1, -1));

        sa.setText("Sabado");
        jd_agregar_doctor.getContentPane().add(sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 311, -1, -1));

        vi.setText("Viernes");
        jd_agregar_doctor.getContentPane().add(vi, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 311, -1, -1));

        ju.setText("Jueves");
        jd_agregar_doctor.getContentPane().add(ju, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 311, -1, -1));

        mi.setText("Miercoles");
        jd_agregar_doctor.getContentPane().add(mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 311, -1, -1));

        ma.setText("Martes");
        jd_agregar_doctor.getContentPane().add(ma, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 311, -1, -1));

        dom.setText("Domingo");
        jd_agregar_doctor.getContentPane().add(dom, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel20.setText("Dias de trabajo");
        jd_agregar_doctor.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 311, -1, -1));

        ta_especialidad.setEditable(false);
        ta_especialidad.setColumns(20);
        ta_especialidad.setRows(5);
        ta_especialidad.setText("Especialidades:");
        jScrollPane2.setViewportView(ta_especialidad);

        jd_agregar_doctor.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 180, 120));

        jButton5.setText("Agregar especialidad");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jd_agregar_doctor.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, 40));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lista de doctores");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Doctores");
        jt_doctores.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jt_doctores);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cb_pacientes.setModel(new DefaultComboBoxModel());

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Seleccione un paciente: ");

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setText("Agregar a un doctor");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        bt_organo.setText("Agregar un organo");
        bt_organo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_organoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_organoMouseEntered(evt);
            }
        });

        jb_alergia.setText("Agregar una alergia");
        jb_alergia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_alergiaMouseClicked(evt);
            }
        });

        bt_enfermedad.setText("Agregar una enfermedad");
        bt_enfermedad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_enfermedadMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_enfermedad)
                    .addComponent(bt_organo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_alergia, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton4)))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(cb_pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(cb_pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(bt_organo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_enfermedad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jb_alergia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jButton6.setText("Guardar Archivo");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Cargar Archivo");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jMenu1.setText("Inicio");

        Agregar.setText("Agregar un paciente");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });
        jMenu1.add(Agregar);

        jMenuItem1.setText("Agregar un doctor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tool");

        jMenuItem2.setText("Acerca de");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)))
                        .addGap(60, 60, 60)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2_nombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_t2_nombreKeyTyped

    private void t2_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2_edadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_t2_edadKeyTyped

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        jd_agregar.setModal(true);
        jd_agregar.pack();
        jd_agregar.setLocationRelativeTo(this);
        jd_agregar.setVisible(true);
    }//GEN-LAST:event_AgregarActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel pacientes = (DefaultComboBoxModel) cb_pacientes.getModel();

        String nombre = t2_nombre.getText();
        int Edad = Integer.parseInt(t2_edad.getText());
        int ID = Integer.parseInt(t2_id.getText());
        double altura = Double.parseDouble(t2_altura.getText()), peso = Double.parseDouble(t2_peso.getText());
        String sexo;
        if (rb_sexo.getSelection() == Masculino) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }

        Paciente paciente = new Paciente(t2_ingreso.getDate(), nombre, Edad, ID, altura, peso, sexo);
        pacientes.addElement(paciente);

        t2_nombre.setText("");
        t2_edad.setText("");
        t2_id.setText("");
        t2_altura.setText("");
        t2_peso.setText("");

    }//GEN-LAST:event_jButton1MouseClicked

    private void t2_alturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2_alturaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_t2_alturaKeyTyped

    private void t2_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_t2_idKeyTyped

    private void t2_pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2_pesoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_t2_pesoKeyTyped

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Delmer Espinal Lab7 progra 2");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void t1_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_nombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_nombreKeyTyped

    private void t1_edadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_edadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_edadKeyTyped

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        // TODO add your handling code here:

        String nombre = t1_nombre.getText();
        int Edad = Integer.parseInt(t1_edad.getText());
        int ID = Integer.parseInt(t1_id.getText());
        double altura = Double.parseDouble(t1_altura.getText()), peso = Double.parseDouble(t1_peso.getText());
        String sexo;
        if (rb_sexo2.getSelection() == masculino) {
            sexo = "Masculino";
        } else {
            sexo = "Femenino";
        }
        int anios = Integer.parseInt(t1_id.getText());
        String horario = t1_entrada.getText() + "-" + t1_salida.getText();
        ArrayList<String> Dias = new ArrayList();
        if (lu.isSelected()) {
            Dias.add("Lunes");
        }
        if (ma.isSelected()) {
            Dias.add("Martes");
        }
        if (mi.isSelected()) {
            Dias.add("Miercoles");
        }
        if (ju.isSelected()) {
            Dias.add("Jueves");
        }
        if (vi.isSelected()) {
            Dias.add("Viernes");
        }
        if (sa.isSelected()) {
            Dias.add("Sabado");
        }
        if (dom.isSelected()) {
            Dias.add("Domingo");
        }

        Doctor doctor = new Doctor(horario, anios, nombre, Edad, ID, altura, peso, sexo);
        doctor.setDiasTrabajo(Dias);

        doctores.add(doctor);
        Recargar();

        t1_nombre.setText("");
        t1_edad.setText("");
        t1_id.setText("");
        t1_altura.setText("");
        t1_peso.setText("");
        t1_entrada.setText("");
        t1_salida.setText("");
        ta_especialidad.setText("Especialidades:");
        especialidades = new ArrayList();

    }//GEN-LAST:event_guardarMouseClicked

    private void t1_alturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_alturaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_alturaKeyTyped

    private void t1_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_idKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_idKeyTyped

    private void t1_pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_pesoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < '.' || c > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_pesoKeyTyped

    private void t1_aniosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_aniosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_aniosKeyTyped

    private void t1_entradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_entradaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < ':' || c > ':')) {
            evt.consume();
        }
    }//GEN-LAST:event_t1_entradaKeyTyped

    private void t1_salidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t1_salidaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && (c < ':' || c > ':')) {
            evt.consume();
        }

    }//GEN-LAST:event_t1_salidaKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_agregar_doctor.setModal(true);
        jd_agregar_doctor.pack();
        jd_agregar_doctor.setLocationRelativeTo(this);
        jd_agregar_doctor.setVisible(true);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jd_agregar_doctor.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jd_agregar.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    ArrayList<String> especialidades = new ArrayList();
    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        String S = JOptionPane.showInputDialog("Ingrese alguna especialidad");
        especialidades.add(S);
        for (String esp : especialidades) {
            ta_especialidad.append("\n" + S);
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try {
            DefaultMutableTreeNode nodo_seleccionado = (DefaultMutableTreeNode) jt_doctores.getSelectionPath().getLastPathComponent();
            Doctor doctor_seleccionado = (Doctor) nodo_seleccionado.getUserObject();

            Paciente paciente = (Paciente) cb_pacientes.getSelectedItem();
            for (Doctor dr : doctores) {
                if (dr.compararDoctor(doctor_seleccionado)) {
                    dr.addPaciente(paciente);
                }
            }
            cb_pacientes.remove(cb_pacientes.getSelectedIndex());
            Recargar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Seleccione solo doctores");
        }


    }//GEN-LAST:event_jButton4MouseClicked

    private void bt_organoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_organoMouseClicked
        // TODO add your handling code here:
        Object[] organos = {"Cerebro", "Corazon", "Estomago", "Higado", "Pancreas", "Pulmones", "Riñon"};
        boolean listo = false;
        String s_organo = (String) JOptionPane.showInputDialog(null, "Seleccione Un Organo",
                "ORGANOS", JOptionPane.QUESTION_MESSAGE, null,
                organos, "Seleccione");

        Color color = JColorChooser.showDialog(this, "Seleccione un color", Color.yellow);
        int potenciado = 0;
        int prueba = 0;
        while (!listo) {

            potenciado = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nivel de potenciado"));
            prueba = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nivel de prueba"));
           
            listo = true;
        }
        ArrayList<String> caracteristicas = new ArrayList();
        char resp = 's';
        while (resp == 's' || resp == 'S') {
            String caract = JOptionPane.showInputDialog("Escriba la caracteristica del organo");
            caracteristicas.add(caract);
            resp = JOptionPane.showInputDialog("Desea agregar otra caracteristica[s/n]: ").charAt(0);

        }

        Organo org;
        switch (s_organo) {
            case "Cerebro":
                org = new Cerebro(color, potenciado, prueba);
                break;
            case "Corazon":
                org = new Corazon(color, potenciado, prueba);
                break;
            case "Estomago":
                org = new Estomago(color, potenciado, prueba);
                break;
            case "Higado":
                org = new Higado(color, potenciado, prueba);
                break;
            case "Pancreas":
                org = new Pancreas(color, potenciado, prueba);
                break;
            case "Pulmones":
                org = new Pulmones(color, potenciado, prueba);
                break;
            default:
                org = new Riñon(color, potenciado, prueba);
                break;

        }

        Paciente pac = (Paciente) cb_pacientes.getSelectedItem();
        org.setCaracteristicas(caracteristicas);
        
        
        
        while (org.getEfectividad()*org.getN_potenciado() > org.getN_prueba()) {

            JOptionPane.showMessageDialog(this, "La multiplicacion del nivel de efectividad con el nivel de potenciado debe"
                    + "de ser menor a el nivel de prueba");
            potenciado = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nivel de potenciado"));
            prueba = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el nivel de prueba"));
            org.setN_potenciado(potenciado);
            org.setN_prueba(prueba);
           
        }
        pac.addOrganos(org);

    }//GEN-LAST:event_bt_organoMouseClicked

    private void bt_enfermedadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_enfermedadMouseClicked
        // TODO add your handling code here:
        String enfermedad = JOptionPane.showInputDialog("Agregue una enfermedad");
        Paciente pac = (Paciente) cb_pacientes.getSelectedItem();
        pac.addEnfermedad(enfermedad);
    }//GEN-LAST:event_bt_enfermedadMouseClicked

    private void jb_alergiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_alergiaMouseClicked
        // TODO add your handling code here:
        String alergia = JOptionPane.showInputDialog("Agregue una alergia");
        Paciente pac = (Paciente) cb_pacientes.getSelectedItem();
        pac.addAlergias(alergia);
    }//GEN-LAST:event_jb_alergiaMouseClicked

    private void bt_organoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_organoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_organoMouseEntered

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        adminBinarios Ap = new adminBinarios("./Archivo.nuevo");
        Ap.setListaPersonas(doctores);
        Ap.escribirArchivo();
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        adminBinarios Ap = new adminBinarios("./Archivo.nuevo");
        try {
            Ap.CargarArchivo();
        } catch (Exception e) {
            Ap.escribirArchivo();
            Ap.CargarArchivo();
        }
        
        
        doctores = Ap.getListaPersonas();
        Recargar();
                
    }//GEN-LAST:event_jButton7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clase_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clase_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clase_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clase_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clase_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Agregar;
    private javax.swing.JRadioButton Femenino;
    private javax.swing.JRadioButton Masculino;
    private javax.swing.JButton bt_enfermedad;
    private javax.swing.JButton bt_organo;
    private javax.swing.JComboBox<String> cb_pacientes;
    private javax.swing.JCheckBox dom;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_alergia;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_agregar_doctor;
    private javax.swing.JTree jt_doctores;
    private javax.swing.JCheckBox ju;
    private javax.swing.JCheckBox lu;
    private javax.swing.JCheckBox ma;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JCheckBox mi;
    private javax.swing.ButtonGroup rb_sexo;
    private javax.swing.ButtonGroup rb_sexo2;
    private javax.swing.JCheckBox sa;
    private javax.swing.JTextField t1_altura;
    private javax.swing.JTextField t1_anios;
    private javax.swing.JTextField t1_edad;
    private javax.swing.JTextField t1_entrada;
    private javax.swing.JTextField t1_id;
    private javax.swing.JTextField t1_nombre;
    private javax.swing.JTextField t1_peso;
    private javax.swing.JTextField t1_salida;
    private javax.swing.JTextField t2_altura;
    private javax.swing.JTextField t2_edad;
    private javax.swing.JTextField t2_id;
    private com.toedter.calendar.JDateChooser t2_ingreso;
    private javax.swing.JTextField t2_nombre;
    private javax.swing.JTextField t2_peso;
    private javax.swing.JTextArea ta_especialidad;
    private javax.swing.JCheckBox vi;
    // End of variables declaration//GEN-END:variables
}
